@php
    $formatAmount = fn (int $value): string => number_format($value / 100, 2, ',', '.');
    $currency = $invoice->currencySymbol();
    $showVat = ($company->is_vat_obligor ?? true) || $invoice->tax_total > 0;
    $fiscal = $invoice->originalFiscalRecord();
@endphp
<!DOCTYPE html><html lang="sr"><head><meta charset="utf-8"><title>Račun {{ $invoice->invoice_number }}</title><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;color:#1c1917;font-family:DejaVu Sans,sans-serif;font-size:8pt}.page{padding:15mm 16mm 18mm}.rule{height:2mm;margin-bottom:9mm;background:#f97316}.header,.identity,.items,.summary{width:100%;border-collapse:collapse}.header td{vertical-align:top}.issuer{width:60%}.document{text-align:right}.eyebrow{color:#c2410c;font-family:DejaVu Sans Mono,monospace;font-size:6.5pt;font-weight:bold;letter-spacing:1px}.company{margin:4px 0 5px;font-size:18pt;font-weight:bold;letter-spacing:-.6px}.doc-number{margin:5px 0;color:#c2410c;font-family:DejaVu Sans Mono,monospace;font-size:20pt;font-weight:bold}.muted{color:#78716c;line-height:1.5}.identity{margin:10mm 0;border-bottom:1px solid #d6d3d1}.identity td{width:50%;padding:0 0 8mm;vertical-align:top}.identity td+td{padding-left:10mm}.recipient{margin:4px 0;font-size:10pt;font-weight:bold}.facts{width:100%;border-collapse:collapse}.facts td{padding:1px 0}.facts td:last-child{text-align:right;font-weight:bold}.items{table-layout:fixed}.items th{padding:7px 4px;background:#292524;color:#fff;font-family:DejaVu Sans Mono,monospace;font-size:6pt;text-align:left;letter-spacing:.5px}.items th:first-child{border-left:3px solid #f97316}.items td{padding:8px 4px;border-bottom:1px solid #e7e5e4;vertical-align:top}.right{text-align:right;white-space:nowrap}.center{text-align:center}.item{font-weight:bold}.desc{margin-top:2px;color:#78716c;font-size:6.7pt}.summary{width:46%;margin:9mm 0 0 auto}.summary td{padding:6px 8px;border-bottom:1px solid #d6d3d1}.summary td:last-child{text-align:right;font-weight:bold}.total td{border:0;background:#f97316;color:#fff;font-size:12pt;font-weight:bold}.note{margin-top:8mm;padding:8px 10px;border:1px solid #fed7aa;background:#fff7ed;white-space:pre-line}.payment{margin-top:7mm;padding:7px 0;border-top:2px solid #292524}.footer{position:fixed;right:16mm;bottom:7mm;left:16mm;color:#a8a29e;font-family:DejaVu Sans Mono,monospace;font-size:6pt}
</style></head><body><div class="page"><div class="rule"></div><table class="header"><tr><td class="issuer"><div class="eyebrow">▣ // IZDAVALAC</div><div class="company">{{ $company->name }}</div><div class="muted">@if($company->address){{ $company->address }}<br>@endif{{ $company->zip }} {{ $company->city }}@if($company->identification_number)<br>JIB: {{ $company->identification_number }}@endif @if($company->vat_number)· PDV: {{ $company->vat_number }}@endif</div></td><td class="document"><div class="eyebrow">RAČUN</div><div class="doc-number">{{ $invoice->invoice_number }}</div><div class="muted">{{ $invoice->date?->format('d.m.Y.') ?? '—' }}</div></td></tr></table>
<table class="identity"><tr><td><div class="eyebrow">KUPAC</div><div class="recipient">{{ $invoice->client?->name ?? '—' }}</div><div class="muted">@if($invoice->client?->address){{ $invoice->client->address }}<br>@endif{{ $invoice->client?->zip }} {{ $invoice->client?->city }}@if($invoice->client?->vat_id)<br>JIB: {{ $invoice->client->vat_id }}@endif</div></td><td><div class="eyebrow">DETALJI</div><table class="facts"><tr><td>Rok plaćanja</td><td>{{ $invoice->due_date?->format('d.m.Y.') ?? '—' }}</td></tr><tr><td>Način plaćanja</td><td>{{ $invoice->payment_type?->label() ?? '—' }}</td></tr><tr><td>Valuta</td><td>{{ $invoice->currency }}</td></tr>@if($fiscal?->fiscal_invoice_number)<tr><td>Fiskalni račun</td><td>{{ $fiscal->fiscal_invoice_number }}</td></tr>@endif</table></td></tr></table>
<table class="items"><thead><tr><th style="width:5%">#</th><th style="width:41%">STAVKA</th><th class="center" style="width:8%">JM</th><th class="right" style="width:8%">KOL.</th><th class="right" style="width:14%">CIJENA</th>@if($showVat)<th class="right" style="width:8%">PDV</th>@endif<th class="right" style="width:{{ $showVat ? '16' : '24' }}%">IZNOS</th></tr></thead><tbody>@foreach($invoice->items as $index => $item) @php($quantity = max(1, (int) $item->quantity))<tr><td class="center">{{ $index + 1 }}</td><td><div class="item">{{ $item->name }}</div>@if($item->description)<div class="desc">{{ $item->description }}</div>@endif</td><td class="center">{{ $item->unit?->value }}</td><td class="right">{{ $item->quantity }}</td><td class="right">{{ $formatAmount((int) round($item->total / $quantity)) }} {{ $currency }}</td>@if($showVat)<td class="right">{{ number_format($item->tax_rate / 100, 2, ',', '.') }}%</td>@endif<td class="right"><strong>{{ $formatAmount($item->total) }} {{ $currency }}</strong></td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>Osnovica</td><td>{{ $formatAmount($invoice->subtotal) }} {{ $currency }}</td></tr>@if($showVat)<tr><td>PDV</td><td>{{ $formatAmount($invoice->tax_total) }} {{ $currency }}</td></tr>@endif<tr class="total"><td>UKUPNO</td><td>{{ $formatAmount($invoice->total) }} {{ $currency }}</td></tr></table>@if($invoice->notes)<div class="note"><div class="eyebrow">NAPOMENA</div>{{ $invoice->notes }}</div>@endif<div class="payment"><div class="eyebrow">PLAĆANJE</div>@forelse($bankAccounts as $account)<strong>{{ $account->bank_name }}</strong> · {{ $account->account_number }}@if($account->swift) · SWIFT {{ $account->swift }}@endif<br>@empty<span class="muted">Podaci za bankovni račun nisu uneseni.</span>@endforelse</div></div><div class="footer">▣ / {{ $company->name }} / {{ $invoice->invoice_number }}</div></body></html>
