@php
    $formatAmount = fn (int $value): string => number_format($value / 100, 2, ',', '.');
    $currency = $invoice->currencySymbol();
    $showVat = ($company->is_vat_obligor ?? true) || $invoice->tax_total > 0;
    $fiscal = $invoice->originalFiscalRecord();
@endphp
<!DOCTYPE html><html lang="sr"><head><meta charset="utf-8"><title>Račun {{ $invoice->invoice_number }}</title><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;background:#0a0f0d;color:#d7f5d0;font-family:DejaVu Sans Mono,monospace;font-size:7.8pt}.page{padding:14mm 15mm 17mm}.prompt{color:#a3e635}.muted{color:#87a78d}.top{padding:9mm 10mm 8mm;border:1px solid #36523a;background:#101a13}.top table,.meta,.items,.totals{width:100%;border-collapse:collapse}.top td{vertical-align:top}.title{margin:7px 0 4px;font-size:20pt;font-weight:bold;letter-spacing:-1px}.number{text-align:right;color:#a3e635;font-size:14pt;font-weight:bold}.meta{margin:7mm 0;border:1px solid #36523a}.meta td{width:50%;padding:7px 8px;vertical-align:top}.meta td+td{border-left:1px solid #36523a}.label{color:#a3e635;font-size:6.5pt;letter-spacing:.8px}.client{margin:4px 0;font-size:10pt;font-weight:bold}.facts td{padding:1px 0}.facts td:last-child{text-align:right;color:#fff}.items{margin-bottom:7mm;border:1px solid #36523a}.items th{padding:6px 4px;background:#1a2d1d;color:#a3e635;font-size:6pt;text-align:left;letter-spacing:.5px}.items td{padding:6px 4px;border-top:1px solid #26402b;vertical-align:top}.right{text-align:right;white-space:nowrap}.center{text-align:center}.name{font-weight:bold;color:#fff}.description{margin-top:2px;color:#87a78d;font-size:6.5pt}.summary{width:43%;margin-left:auto}.totals{border:1px solid #36523a}.totals td{padding:6px 7px;border-top:1px solid #36523a}.totals td:last-child{text-align:right;color:#fff}.total td{background:#a3e635;color:#0a0f0d!important;font-size:11pt;font-weight:bold}.note,.payment{margin-top:7mm;padding:7px 9px;border-left:2px solid #a3e635;background:#101a13;white-space:pre-line}.footer{position:fixed;right:15mm;bottom:7mm;left:15mm;color:#5c7b63;font-size:6pt}
</style></head><body><div class="page">
<div class="top"><table><tr><td><div class="prompt">▸ račun / izdan</div><div class="title">RAČUN</div><div class="muted">{{ $company->name }} · @if($company->identification_number)JIB {{ $company->identification_number }}@endif<br>@if($company->address){{ $company->address }}, {{ $company->zip }} {{ $company->city }}@endif</div></td><td class="number">#{{ $invoice->invoice_number }}<br><span class="muted" style="font-size:7pt">{{ $invoice->date?->format('d.m.Y.') ?? '—' }}</span></td></tr></table></div>
<table class="meta"><tr><td><div class="label">// KUPAC</div><div class="client">{{ $invoice->client?->name ?? '—' }}</div><div class="muted">@if($invoice->client?->address){{ $invoice->client->address }}<br>@endif {{ $invoice->client?->zip }} {{ $invoice->client?->city }}@if($invoice->client?->vat_id)<br>JIB {{ $invoice->client->vat_id }}@endif</div></td><td><div class="label">// PODACI</div><table class="facts"><tr><td>rok</td><td>{{ $invoice->due_date?->format('d.m.Y.') ?? '—' }}</td></tr><tr><td>plaćanje</td><td>{{ $invoice->payment_type?->label() ?? '—' }}</td></tr><tr><td>valuta</td><td>{{ $invoice->currency }}</td></tr>@if($fiscal?->fiscal_invoice_number)<tr><td>fiskalni</td><td>{{ $fiscal->fiscal_invoice_number }}</td></tr>@endif</table></td></tr></table>
<table class="items"><thead><tr><th style="width:5%">ID</th><th style="width:43%">STAVKA</th><th class="center" style="width:7%">JM</th><th class="right" style="width:8%">KOL.</th><th class="right" style="width:14%">CIJENA</th>@if($showVat)<th class="right" style="width:8%">PDV</th>@endif<th class="right" style="width:{{ $showVat ? '15' : '23' }}%">IZNOS</th></tr></thead><tbody>@foreach($invoice->items as $index => $item) @php($quantity = max(1, (int) $item->quantity))<tr><td class="center">{{ str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT) }}</td><td><div class="name">{{ $item->name }}</div>@if($item->description)<div class="description">{{ $item->description }}</div>@endif</td><td class="center">{{ $item->unit?->value }}</td><td class="right">{{ $item->quantity }}</td><td class="right">{{ $formatAmount((int) round($item->total / $quantity)) }} {{ $currency }}</td>@if($showVat)<td class="right">{{ number_format($item->tax_rate / 100, 2, ',', '.') }}%</td>@endif<td class="right"><strong>{{ $formatAmount($item->total) }} {{ $currency }}</strong></td></tr>@endforeach</tbody></table>
<div class="summary"><table class="totals"><tr><td>osnovica</td><td>{{ $formatAmount($invoice->osnovica) }} {{ $currency }}</td></tr>@if($showVat)<tr><td>pdv</td><td>{{ $formatAmount($invoice->tax_total) }} {{ $currency }}</td></tr>@endif<tr class="total"><td>UKUPNO</td><td>{{ $formatAmount($invoice->total) }} {{ $currency }}</td></tr></table></div>
@if($invoice->notes)<div class="note"><span class="label">// NAPOMENA</span><br>{{ $invoice->notes }}</div>@endif<div class="payment"><span class="label">// PLAĆANJE</span><br>@forelse($bankAccounts as $account)<strong>{{ $account->bank_name }}</strong> · {{ $account->account_number }}@if($account->swift) · SWIFT {{ $account->swift }}@endif<br>@empty<span class="muted">Podaci za bankovni račun nisu uneseni.</span>@endforelse</div></div><div class="footer">✓ · {{ $company->name }} · {{ $invoice->invoice_number }}</div></body></html>
