@php
    $formatAmount = fn (int $value): string => number_format($value / 100, 2, ',', '.');
    $currency = $invoice->currencySymbol();
    $showVat = ($company->is_vat_obligor ?? true) || $invoice->tax_total > 0;
    $fiscal = $invoice->originalFiscalRecord();
@endphp
<!DOCTYPE html><html lang="sr"><head><meta charset="utf-8"><title>Račun {{ $invoice->invoice_number }}</title><style>
@page{margin:0}*{box-sizing:border-box}body{margin:0;color:#14213d;font-family:DejaVu Sans,sans-serif;font-size:8pt}.page{padding:14mm 16mm 18mm}.bar{height:5mm;margin:0 -16mm 10mm;background:#2563eb}.header,.profiles,.items,.totals{width:100%;border-collapse:collapse}.header>tbody>tr>td{vertical-align:top}.company{width:59%}.doc{text-align:right}.kicker{color:#2563eb;font-family:DejaVu Sans Mono,monospace;font-size:6.5pt;font-weight:bold;letter-spacing:1px}.name{margin:4px 0;font-size:17pt;font-weight:bold}.doc-number{margin:5px 0;color:#2563eb;font-family:DejaVu Sans Mono,monospace;font-size:18pt;font-weight:bold}.subtle{color:#64748b;line-height:1.5}.profiles{margin:9mm 0;table-layout:fixed}.profiles>tbody>tr>td{width:50%;padding:8px 10px;vertical-align:top;background:#f8fafc;border-top:2px solid #2563eb}.profiles>tbody>tr>td+td{border-left:7mm solid #fff}.profile-name{margin:4px 0;font-size:10pt;font-weight:bold}.facts{width:100%;border-collapse:collapse}.facts td{padding:1px 0}.facts td:last-child{text-align:right;font-weight:bold}.items{border-top:2px solid #14213d;table-layout:fixed}.items th{padding:7px 4px;color:#2563eb;font-family:DejaVu Sans Mono,monospace;font-size:6pt;text-align:left;letter-spacing:.6px}.items td{padding:7px 4px;border-top:1px solid #dbe5f1;vertical-align:top}.right{text-align:right;white-space:nowrap}.center{text-align:center}.item{font-weight:bold}.desc{margin-top:2px;color:#64748b;font-size:6.7pt}.total-area{margin-top:8mm}.totals{width:45%;margin-left:auto;border:1px solid #bfdbfe}.totals td{padding:6px 8px}.totals td:last-child{text-align:right;font-weight:bold}.grand td{background:#2563eb;color:#fff;font-size:11pt}.note{margin-top:8mm;padding:7px 10px;border-top:1px solid #bfdbfe;background:#eff6ff;white-space:pre-line}.payment{margin-top:7mm;padding-top:5mm;border-top:1px solid #dbe5f1}.footer{position:fixed;right:16mm;bottom:7mm;left:16mm;color:#94a3b8;font-family:DejaVu Sans Mono,monospace;font-size:6pt}
</style></head><body><div class="page"><div class="bar"></div><table class="header"><tr><td class="company"><div class="kicker">PROTOCOL / INVOICE</div><div class="name">{{ $company->name }}</div><div class="subtle">@if($company->address){{ $company->address }}<br>@endif{{ $company->zip }} {{ $company->city }}@if($company->identification_number)<br>JIB: {{ $company->identification_number }}@endif @if($company->vat_number)· PDV: {{ $company->vat_number }}@endif</div></td><td class="doc"><div class="kicker">DOCUMENT ID</div><div class="doc-number">{{ $invoice->invoice_number }}</div><div class="subtle">Izdano {{ $invoice->date?->format('d.m.Y.') ?? '—' }}</div></td></tr></table>
<table class="profiles"><tr><td><div class="kicker">CLIENT_PROFILE</div><div class="profile-name">{{ $invoice->client?->name ?? '—' }}</div><div class="subtle">@if($invoice->client?->address){{ $invoice->client->address }}<br>@endif{{ $invoice->client?->zip }} {{ $invoice->client?->city }}@if($invoice->client?->vat_id)<br>JIB: {{ $invoice->client->vat_id }}@endif</div></td><td><div class="kicker">TRANSACTION</div><table class="facts"><tr><td>Rok plaćanja</td><td>{{ $invoice->due_date?->format('d.m.Y.') ?? '—' }}</td></tr><tr><td>Način plaćanja</td><td>{{ $invoice->payment_type?->label() ?? '—' }}</td></tr><tr><td>Valuta</td><td>{{ $invoice->currency }}</td></tr>@if($fiscal?->fiscal_invoice_number)<tr><td>Fiskalni račun</td><td>{{ $fiscal->fiscal_invoice_number }}</td></tr>@endif</table></td></tr></table>
<table class="items"><thead><tr><th style="width:5%">#</th><th style="width:40%">ITEM</th><th class="center" style="width:8%">JM</th><th class="right" style="width:8%">QTY</th><th class="right" style="width:14%">RATE</th>@if($showVat)<th class="right" style="width:9%">PDV</th>@endif<th class="right" style="width:{{ $showVat ? '16' : '25' }}%">AMOUNT</th></tr></thead><tbody>@foreach($invoice->items as $index => $item) @php($quantity = max(1, (int) $item->quantity))<tr><td class="center">{{ $index + 1 }}</td><td><div class="item">{{ $item->name }}</div>@if($item->description)<div class="desc">{{ $item->description }}</div>@endif</td><td class="center">{{ $item->unit?->value }}</td><td class="right">{{ $item->quantity }}</td><td class="right">{{ $formatAmount((int) round($item->total / $quantity)) }} {{ $currency }}</td>@if($showVat)<td class="right">{{ number_format($item->tax_rate / 100, 2, ',', '.') }}%</td>@endif<td class="right"><strong>{{ $formatAmount($item->total) }} {{ $currency }}</strong></td></tr>@endforeach</tbody></table>
<div class="total-area"><table class="totals"><tr><td>Osnovica</td><td>{{ $formatAmount($invoice->subtotal) }} {{ $currency }}</td></tr>@if($showVat)<tr><td>PDV</td><td>{{ $formatAmount($invoice->tax_total) }} {{ $currency }}</td></tr>@endif<tr class="grand"><td>UKUPNO</td><td>{{ $formatAmount($invoice->total) }} {{ $currency }}</td></tr></table></div>@if($invoice->notes)<div class="note"><div class="kicker">MESSAGE</div>{{ $invoice->notes }}</div>@endif<div class="payment"><div class="kicker">PAYMENT ROUTING</div>@forelse($bankAccounts as $account)<strong>{{ $account->bank_name }}</strong> · {{ $account->account_number }}@if($account->swift) · SWIFT {{ $account->swift }}@endif<br>@empty<span class="subtle">Podaci za bankovni račun nisu uneseni.</span>@endforelse</div></div><div class="footer">PROTOCOL VERIFIED · {{ $company->name }} · {{ $invoice->invoice_number }}</div></body></html>
